apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clickhouse

resources:
- https://raw.githubusercontent.com/Altinity/clickhouse-operator/refs/heads/master/deploy/operator/clickhouse-operator-install-bundle.yaml

- clickhouse-installation.yaml
patchesJson6902:
- path: resources-limit-patch.yaml
  target:
    version: v1
    kind: Deployment
    name: clickhouse-operator