apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/crud-web-apps/volumes/manifests/overlays/istio?ref=v1.10.0 # tag=v1.4.0
- github.com/kubeflow/manifests/apps/pvcviewer-controller/upstream/default?ref=v1.10.0
images:
- name:  docker.io/kubeflownotebookswg/volumes-web-app
  newName:  docker.io/kubeflownotebookswg/volumes-web-app
  newTag: v1.10.1

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: volumes-web-app-deployment
  patch: |-
    - op: add
      path: /spec/template/metadata/labels/app.architecture
      value: kubeflow-front-end
