apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../workflows
- regcred.yaml
- minio_artifact_secret.yaml
patchesStrategicMerge:
  - clusterrolebinding-patch.yaml
# - ingress.yaml
