apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: qdrant
    repo: https://qdrant.to/helm
    version: 0.7.6
    valuesInline:
      service:
        type: LoadBalancer
      

