apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:

# ---------------- secrets -----------------------

# ---------------- network and storage ressources ------------------
# - argocd-applications/external-dns-controller.yaml
# - argocd-applications/rook-ceph.yaml
# - argocd-applications/nfs-provisioner.yaml
# - argocd-applications/nginx.yaml
# argocd-applications/nvidia-gpu-operator.yaml

# ----------------- CI/CD  -------------------------------
#------------------ cloud control plane ----------------------------
#- argocd-applications/cross-plane.yaml

# ----------------- workflow resources -----------------------------
# argocd-applications/airflow.yaml
# - argocd-applications/prefect.yaml

# ------------------ policies --------------------------------------
# - argocd-applications/kubed.yaml
# - argocd-applications/kyverno.yaml
# ------------------ project-management ----------------------------

#--------------------apps-low-code----------------------------------
#- argocd-applications/tooljet.yaml

# ------------------ private registry ------------------------------

# --------------- Istio and authentication environments ------------
# - argocd-applications/minio-operator.yaml

# ---------------- API GATEWAY -------------------------------------

# ------------------- monitoring ----------------------------------
# ------------------- kubeflow ------------------------------------

#  argocd-applications/modeldb.yaml

# ---------------- Monitoring and logging ------------------------
#- argocd-applications/monitoring-resources.yaml
#- argocd-applications/kube-prometheus-stack.yaml
#- argocd-applications/loki-stack.yaml
#- argocd-applications/kiali.yaml
#- argocd-applications/kiali-instance.yaml
#- argocd-applications/elastic.yaml
# argocd-applications/elastic-cluster.yaml
#- argocd-applications/jaeger-operator.yaml
#- argocd-applications/jaeger-cluster.yaml
#- argocd-applications/cassandra-operator.yaml
# argocd-applications/cassandra-cluster.yaml
# - argocd-applications/cassandra-bitnami.yaml

#- argocd-applications/skywalking-operator.yaml
#- argocd-applications/opentelemetry-operator.yaml
#------------------ security -----------------------
- argocd-applications/trivy-operator.yaml
#- argocd-applications/falco.yaml
# - argocd-applications/conjur-oss.yaml
#- argocd-applications/vault.yaml
# - argocd-applications/victoria-metrics.yaml
# argocd-applications/grafana.yaml

# ----------------- data visualization ---------------------------

# --------------------llm------------------------------------------
# ----------------- data-lake data-processing --------------------
# - argocd-applications/airbyte.yaml
# - argocd-applications/polaris.yaml
# - argocd-applications/trino.yaml

# - argocd-applications/druid-cluster.yaml
# argocd-applications/postgres-operator-ui.yaml
# fetaure ingestion and management
#- argocd-applications/ozone.yaml
#- argocd-applications/apache-doris.yaml
# - argocd-applications/fluid.yaml
# - argocd-applications/alluxio.yaml
# inference-services
#Â - argocd-applications/inference-services.yaml
# --------------------metadata-management-------------------------
#  argocd-applications/openmetadata-deps.yaml
#- argocd-applications/datahub.yaml
#- argocd-applications/datahub-prerequisites.yaml
# -----------------------------------------------------
# customer interface
# argocd-applications/wordpress.yaml

# ------------------------erp--------------------------------------
- argocd-applications/apps-secrets.yaml
#- argocd-applications/apps-test-local.yaml
# - argocd-applications/apps-migration.yaml
- argocd-applications/metallb-local.yaml
- argocd-applications/openebs.yaml
- argocd-applications/sealed-secrets.yaml
- argocd-applications/apps-network-local.yaml
- argocd-applications/nvidia-device-plugin.yaml
- argocd-applications/argocd.yaml
- argocd-applications/argo-events.yaml
- argocd-applications/argo-workflows.yaml
- argocd-applications/airflow-secret.yaml
- argocd-applications/reflector.yaml
- argocd-applications/namespaces-labels.yaml
- argocd-applications/kyverno-policies.yaml
- argocd-applications/wekan.yaml
- argocd-applications/n8n.yaml
- argocd-applications/harbor.yaml
- argocd-applications/istio.yaml
- argocd-applications/istio-local-resources.yaml
- argocd-applications/istio-operator.yaml
- argocd-applications/oidc-auth-on-cluster-keycloak.yaml
- argocd-applications/apisix.yaml
- argocd-applications/metrics-server.yaml
- argocd-applications/kubeflow-roles-namespaces.yaml
- argocd-applications/cert-manager.yaml
- argocd-applications/certificate.yaml
- argocd-applications/knative-eventing.yaml
- argocd-applications/knative-serving.yaml
- argocd-applications/kafka.yaml
- argocd-applications/kafka-clusters.yaml
- argocd-applications/camel-k.yaml
- argocd-applications/kafka-source.yaml
- argocd-applications/pipelines.yaml
- argocd-applications/kserve.yaml
- argocd-applications/katib.yaml
- argocd-applications/central-dashboard.yaml
- argocd-applications/pod-defaults.yaml
- argocd-applications/jupyter-web-app.yaml
- argocd-applications/notebook-controller.yaml
- argocd-applications/profile-controller_access-management.yaml
- argocd-applications/tensorboard-controller.yaml
- argocd-applications/tensorboards-web-app.yaml
- argocd-applications/volumes-web-app.yaml
- argocd-applications/training-operator.yaml
- argocd-applications/user-namespace.yaml
- argocd-applications/model-registry.yaml
- argocd-applications/superset.yaml
- argocd-applications/superset-dashboard-web.yaml
- argocd-applications/superset-dashboard-web-pages.yaml
- argocd-applications/ollama.yaml
- argocd-applications/litellm.yaml
- argocd-applications/flowiseai.yaml
- argocd-applications/opik.yaml
- argocd-applications/druid-operator.yaml
- argocd-applications/nessie.yaml
- argocd-applications/druid-cluster.yaml
- argocd-applications/clickhouse.yaml
- argocd-applications/hive-metastore.yaml
- argocd-applications/spark-operator.yaml
- argocd-applications/postgres-operator.yaml
- argocd-applications/cloudnative-pg.yaml
- argocd-applications/feast.yaml
- argocd-applications/feast-redis.yaml
- argocd-applications/flink-operator.yaml
- argocd-applications/qdrant.yaml
- argocd-applications/minio-operator.yaml
- argocd-applications/nfs-server.yaml
- argocd-applications/openmetadata.yaml
- argocd-applications/label-studio.yaml
- argocd-applications/etcd-backup.yaml
- argocd-applications/olm.yaml

# ------------------- priority classes -----------------------------
- argocd-applications/priority-classes.yaml
# -------------------------------------------
- argocd-applications/istio-control.yaml
- argocd-applications/istio-system.yaml
