apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - https://github.com/apache/camel-k/config/manager?ref=release-2.1.x
# - https://github.com/apache/camel-k/config/crd?ref=release-2.1.x
# - https://github.com/apache/camel-k/config/rbac?ref=release-2.1.x
- integration-platform.yaml
- docker-regcred.yaml
- regcred.yaml
