apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- auth-gateway-cloud-api.yaml
- http-route.yaml
- auth-allow-redirect.yaml
- auth-authorization-policy.yaml
- oauth2-proxy-signout-virtual-service.yaml