apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- gateway-authorizationpolicy-applications-local.yaml
#- gateway-authorizationpolicy-kubeflow-local.yaml
- authorizationpolicy.istio-ingressgateway-oauth2-proxy.yaml
- authorizationpolicy.istio-ingressgateway-require-jwt.yaml
- authorizationpolicy-harbor.yaml
- kubeflow-gateway.yaml