apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/crud-web-apps/tensorboards/manifests/overlays/istio?ref=v1.10.0 # tag=v1.5.0

images:
- name: docker.io/kubeflownotebookswg/tensorboards-web-app
  newName: docker.io/kubeflownotebookswg/tensorboards-web-app
  newTag: v1.10.0

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: tensorboards-web-app-deployment
  patch: |-
    - op: add
      path: /spec/template/metadata/labels/app.architecture
      value: kubeflow-front-end
