apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace-superset-label.yaml
patchesJson6902:
- target:
    version: v1
    kind: Namespace
    name: frederik-coquelet
  path: namespace-frederik-patch.json