apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubeflow/kubeflow/components/admission-webhook/manifests/overlays/cert-manager?ref=v1.10.0 # tag=v1.5.0

images:
- name: docker.io/kubeflownotebookswg/poddefaults-webhook
  newName: docker.io/kubeflownotebookswg/poddefaults-webhook
  newTag: v1.10.0
