apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- namespace.yaml
- github.com/argoproj/argo-workflows/manifests/base/argo-server?ref=v3.4.17
#- github.com/argoproj/argo-workflows/manifests/cluster-install/workflow-controll?er-rbac
- github.com/argoproj/argo-workflows/manifests/cluster-install/argo-server-rbac?ref=v3.4.17
patchesStrategicMerge:
- argo-server-insecure-patch.yaml
namespace: kubeflow
images:
- name: quay.io/argoproj/argocli
  newName: quay.io/argoproj/argocli
  newTag: v3.4.17
