apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: kubeflow
  annotations:
    kubernetes.io/ingress.class: nginx
    
spec:
  rules:
  - host: minio.192.168.0.101.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-service-console
            port: 
              name: http-console