apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
-  https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.7.2/components.yaml

patchesJson6902:
- target:
    version: v1 # apiVersion
    kind: Deployment
    name: metrics-server
    namespace: kube-system
  path: kubelet-address-patch.yaml
