apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/profile-controller/config/overlays/kubeflow?ref=v1.10.0 # tag=v1.5.0
images:
- name: ghcr.io/kubeflow/kubeflow/kfam
  newName: ghcr.io/kubeflow/kubeflow/kfam
  newTag: latest

