apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - https://github.com/operator-framework/operator-lifecycle-manager/releases/latest/download/crds.yaml
  - https://github.com/operator-framework/operator-lifecycle-manager/releases/latest/download/olm.yaml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.3.5/kubernetes/kubernetes.yml
