apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-eventing
resources:

#- github.com/kubeflow/manifests/common/knative/knative-eventing/base
- https://github.com/knative/operator/releases/download/knative-v1.14.3/operator.yaml
- knative-eventing-cr.yaml