apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/fredcoq/manifests/contrib/modeldb/base?ref=57520cfa6d9ce765ace159f844ec366d15700a2d

namespace:

  kubeflow
