apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: istio-ingressgateway-require-jwt
  namespace: istio-system
spec:
  action: DENY
  selector:
    matchLabels:
      app: istio-ingressgateway
  rules:
  # Deny requests that don't have a verified JWT (from a RequestAuthentication)
  # Note, even user requests that have been authenticated by oauth2-proxy will have a JWT,
  # because oauth2-proxy injects a Dex JWT into the request.
  - to:
    - operation:
        hosts:
          - kubeflow.kubefrog.ai
          - kubecost.kubefrog.ai
          - serving.kubefrog.ai
          - '*.serving.kubefrog.ai'
        notPaths:
        # Exclude dex paths, otherwise users won't be able to log in.
          - /oauth2/*
    when:
    - key: request.auth.claims[iss]
      notValues: ["*"]
    #from:
    #- source:
    #    notRequestPrincipals: ["*"]