apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: istio-ingressgateway-oauth2-proxy
  namespace: istio-system
spec:
  action: CUSTOM
  provider:
    name: oauth2-proxy-cloud
  selector:
    matchLabels:
      app: istio-ingressgateway
  rules:
  # We ONLY authenticate requests that DON'T have an `Authorization` header using oauth2-proxy.
  # This is because we use RequestAuthentication to authenticate requests with an `Authorization` header.
  - to:
    - operation:
        hosts:
          - kubeflow.kubefrog.ai
          - kubecost.kubefrog.ai
          - serving.kubefrog.ai
          - '*.serving.kubefrog.ai'
        notPaths:
    #    # Exclude dex paths, otherwise users won't be able to log in.
         - /oauth2/*
      when:
    - key: request.headers[authorization]
      notValues: ["*"]

