apiVersion: v1
kind: Service
metadata:
  name: flowiseai
  namespace: flowiseai
spec:
  selector:
    app: flowiseai
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000