apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgress.yaml
helmCharts:
  - name: nessie
    repo: https://charts.projectnessie.org
    version: 0.95.0
    valuesFile: values.yaml
    namespace: nessie

