apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operators
helmCharts:
  - name: redis-operator
    version: 0.23.0
    repo: https://ot-container-kit.github.io/helm-charts/
    releaseName: redis-operator
    namespace: operators
    valuesInline:
      redisOperator:
        webhook: true
      certmanager:
        enabled: true
    valuesFile: values.yaml