apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datahub
resources:
  - mysql-creds.yaml
  - neo4j-creds.yaml
helmCharts:
  - name: datahub-prerequisites
    repo: https://helm.datahubproject.io
    version: 0.0.18
    releaseName: prerequisites
    valuesFile: values.yaml
    namespace: datahub



