apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- gateway-authorizationpolicy-applications-cloud.yaml
- gateway-authorizationpolicy-kubeflow-cloud.yaml
- authorizationpolicy.istio-ingressgateway-oauth2-proxy.yaml
- authorizationpolicy.istio-ingressgateway-require-jwt.yaml
- kubeflow-gateway-cloud.yaml
