apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubeflow/manifests/applications/kserve/kserve?ref=v1.10.2
- https://github.com/kubeflow/manifests/apps/kserve/models-web-app/overlays/kubeflow?ref=v1.10.0

patchesStrategicMerge:
  - configmap_server_patch.yaml
  - inference-patch.yaml
  - default-cluster-storage-patch.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: kserve-models-web-app
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/securityContext
      value: {"seccompProfile": {"type": "RuntimeDefault"},
              "allowPrivilegeEscalation": false,
              "capabilities": {"drop": ["ALL"]},
              "runAsNonRoot": false
              }
    - op: add
      path: /spec/template/spec/securityContext
      value: {"seccompProfile": {"type": "RuntimeDefault"}}
- target:
    group: apps
    version: v1
    kind: Deployment
    name: kserve-controller-manager
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/securityContext
      value: {"seccompProfile": {"type": "RuntimeDefault"},
              "allowPrivilegeEscalation": false,
              "capabilities": {"drop": ["ALL"]},
              "runAsNonRoot": true
              }
    - op: add
      path: /spec/template/spec/securityContext
      value: {"seccompProfile": {"type": "RuntimeDefault"}}
- target:
    group: apps
    version: v1
    kind: Deployment
    name: kserve-localmodel-controller-manager
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/securityContext
      value: {"seccompProfile": {"type": "RuntimeDefault"},
              "allowPrivilegeEscalation": false,
              "capabilities": {"drop": ["ALL"]},
              "runAsNonRoot": true
              }
    - op: add
      path: /spec/template/spec/securityContext
      value: {"seccompProfile": {"type": "RuntimeDefault"}}



#patchesStrategicMerge:
#- patches/inferenceservice-config.yaml

