apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

- https://github.com/operator-framework/operator-lifecycle-manager/releases/latest/download/crds.yaml?timeout=120
- https://github.com/operator-framework/operator-lifecycle-manager/releases/latest/download/olm.yaml?timeout=120
