apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postrgres-manifest.yaml
helmCharts:
  - name: superset
    repo: https://apache.github.io/superset/
    version: 0.15.2
    valuesFile: values.yaml
    namespace: superset
    
patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Namespace
      name: superset
    patch: |-
      - op: add
        path: /metadata/labels/istio-injection
        value: enabled

