
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- infisical-secret.yaml
- namespace.yaml
- infisical-cloudflare-secret.yaml
- infisical-kubefrog-secret.yaml
helmCharts:
- name: infisical-standalone
  version: v1.7.1
  repo: https://dl.cloudsmith.io/public/infisical/helm/charts/
  releaseName: infisical
  namespace: infisical
  valuesInline:
    ingress:
      enabled: false
      nginx:
        enabled: false