apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubeflow/manifests/apps/training-operator/upstream/overlays/kubeflow?ref=v1.10.1

patchesJson6902:
- path: resources-limit-patch.yaml
  target:
    version: v1
    kind: Deployment
    name: training-operator
