apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - time-slicing-config.yaml
#- nvidia-device-plugin.yaml
helmCharts:
  - name: nvidia-device-plugin
    version: 0.17.1
    repo: https://nvidia.github.io/k8s-device-plugin
    releaseName: nvidia-device-plugin
    namespace: kube-system
    valuesInline: 
      config:
        name: time-slicing-config
  
