# kustomization file for keycloak themes
# files login.ftl style.css theme.properties are stored in a genrated configmap
kind: Kustomization

configMapGenerator:
  - name: keycloak-theme
    namespace: auth
    behavior: create
    files:
      - login.ftl
      - style.css
      - theme.properties
    options:
      disableNameSuffixHash: true


