apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubernetes/ingress-nginx/deploy/static/provider/cloud?ref=fb72fcd81772fb3eca923897aec2d92fa5bdff41
- monitoring/service-monitor.yaml
# gitlab-tcp-configmap.yaml
#patchesStrategicMerge:
patchesStrategicMerge:
- loadbalancerIP-service-patch.yaml
- default-ingress-class.yaml
- deployment_patch.yaml
# gitlab-service-patch.yaml
