apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

# - argocd-ingress.yaml
# - argocd-repo-creds.yaml
# - argocd-repositories.yaml
resources:
- namespace.yaml
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v3.2.6&timeout=90s
- argocd-gateway.yaml
- argocd-virtualservice.yaml
- argocd-webhook-virtualservice.yaml
- githubcred.yaml
- harborcred.yaml
- kubefrog-local-secret.yaml
- kubefrog-ovh-secret.yaml
- fredcoq-secret.yaml
# - argocd-service-monitor.yaml
#- add-custom-kustomize.yaml
# - argocd-server-insecure-patch.yaml
patches:
- path: configmap-knownhost-local-patch.yaml
- path: add-ressource-repo-server.yaml
- path: argocd-cmd-params-cm-patch.yaml
- path: configmap-patch.yaml
- path: configmap-tls-certs-patch.yaml
- path: github-webhook-secret.yaml
