apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-control
helmCharts:

  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    releaseName: "prod"
    namespace: istio-control
    version: 1.26.2
    valuesFile: values.yaml