apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: oauth2-proxy
    repo: https://oauth2-proxy.github.io/manifests
    releaseName: "oauth2-proxy"
    namespace: oauth2-proxy
    version: 7.10.4
    valuesFile: values.yaml
resources:
  - redis.yaml
  - redis-secret.yaml
  - oauth2-proxy-service-account.yaml
  - oauth2-proxy-secret.yaml
  