apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - auth-gateway-cloud.yaml
#- oauth2-proxy-signout-virtual-service-cloud.yaml
- oauth2-proxy-koidc-cloud.yaml
- oauth2-proxy-serviceaccount.yaml