apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: wekan
    repo: https://wekan.github.io/charts
    version: 7.95.0
    valuesInline:
      mongodb:
        replicaCount: 1
      resources:
        requests:
          cpu: 50m
      service:
        type: ClusterIP
      autoscaling:
        enabled: false
      ingress:
        enabled: false
      root_url: https://wekan.kubefrog.ai
      env:
        - name: MAIL_URL
          value: smtp://frederik.coquelet@gmail.com:xlenosuqrsclibgf@smtp.gmail.com:25/

patchesStrategicMerge:
  
  - deploy-patch.yaml
 