apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: knative-eventing
resources:
- https://github.com/knative-sandbox/eventing-kafka/releases/download/knative-v1.9.1/source.yaml
# - https://github.com/knative-sandbox/eventing-kafka/releases/download/knative-v1.9.1/source-post-install.yaml
# - channel-consolidated.yaml
- addressable-resolver.yaml
# - eventing-kafka-controller.yaml
 
