apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kubeflow-gateway-cert.yaml
- kubeflow-gateway-cert-ai.yaml
- ollama-gateway-cert-local.yaml
- minio-tenant-cert.yaml
# - kubeflow-gateway-cert-test.yaml
