apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- event-sources.yaml
# - event-source-ingress.yaml
- sensors.yaml
- sensor-mnist-transformer.yaml
- githubcred.yaml
- argo-events-gateway.yaml
- argo-events-virtualservice.yaml
# - event-authorizationpolicy.yaml
namespace: argo-events

