apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - kubeflow-self-signed-issuer.yaml
  - kubeflow-ca-issuer.yaml
  - kubeflow-cloudflare-issuer.yaml
  - kubeflow-cloudflare-cluster-issuer.yaml
  - ca-certificate.yaml
  - cloudflare-api-token-secret.yaml
  - cloudflare-api-token-secret-istio.yaml