apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: crossplane
    repo: https://charts.crossplane.io/stable
    version: 1.15.1
    # valuesFile: 
    releaseName: "prod"
    namespace: crossplane-system
#resources:
  #- awscred.yaml
  #- providers
